### ISSUE TITLE
TypeError: exists is not a function

### ISSUE THREAD

**Issue by vmalepati1** [DcentWallet/dcent-cli-connector#1]
Hi friends,

I am using this module with a React application which needs to interface with the wallet. My nodejs version is v18.14.0. I am currently getting the following exception when I import `dcent-cli-connector`:

```
    Uncaught TypeError: exists is not a function
    at Function.getRoot (bindings.js:202:1)
    at bindings (bindings.js:82:1)
    at Object.<anonymous> (index.js:13:1)
    at ./node_modules/usb-detection/index.js (index.js:111:1)
    at __webpack_require__ (bootstrap:784:1)
    at fn (bootstrap:150:1)
    at index.js:1:1
    at Object.<anonymous> (index.js:1:1)
    at ./node_modules/dcent-cli-connector/dist/index.js (index.js:11:1)
    at __webpack_require__ (bootstrap:784:1)
    at fn (bootstrap:150:1)
    at ./src/pages/Dashboard.js (index.js:32:1)
    at __webpack_require__ (bootstrap:784:1)
    at fn (bootstrap:150:1)
    at ./src/pages/HomePage.js (Dashboard.js:37:1)
    at __webpack_require__ (bootstrap:784:1)
    at fn (bootstrap:150:1)
    at ./src/index.js (transactions.js:84:1)
    at __webpack_require__ (bootstrap:784:1)
    at fn (bootstrap:150:1)
    at 1 (dashboard.scss?b299:45:1)
    at __webpack_require__ (bootstrap:784:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:109
```

**Comment by vmalepati1** [comment]
I realized I was running this in a React script instead of the backend server, which was causing the issue
